//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bmbox.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transactions
    {
        public int Id { get; set; }
        public string UserEmail { get; set; }
        public long Date { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
